repo_url: https://github.com/ramonpzg/comparisons
repo_name: Data Tools Comparisons

site_name: "ML Comparisons"
site_url: https://ramonpzg.github.io/comparisons
site_description: Comparisons between different tools, approaches, techniques, and anything in between in the space of machine learning.
site_author: Ramon Perez
site_image: http://www.w3.org/2000/svg
# site_image_alt: Image explaining what f"Do {X} with Data" covers.

copyright: Copyright &copy; 2023 Ramon Perez


theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    - scheme: slate
      primary: pink
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    # - navigation.tabs.sticky
    - content.tabs.link
    - toc.follow
    - navigation.top
  font:
    text: Roboto
    # code: Roboto Mono


nav:
  - Home: index.md
  - Serving Tools:
    - serving/index.md
    - MLServer vs Ray Serve: serving/00_serving_tools.md
    # - Python Installation: analytics/01_python_installation.md
    # - Anaconda Installation: analytics/02_anaconda_installation.md
    # - 03_git_installation: analytics/03_git_installation.md
    # - 01 Jupyter Intro: analytics/01_jupyter_intro.md
  # - Product: explanation.md
  # - Data Engineering:
  #   - data_eng/index.md
  #   - Intro to Data Engineering: data_eng/06_terminal.md
  - Explainable AI:
    - xai/index.md
    - Alibi Explain vs Interpret ML: xai/00_alibix_interpret.md
    # - 03 Data Structures: programming/03_structures.md
    # - 04 Tools: programming/04_tools.md
    # - 05 Control Flow: programming/05_control_flow.md
    # - 06 The Terminal: programming/06_terminal.md
    # - 07 Version Control: programming/07_version_control.md
    # - 08 Intermediate Python: programming/08_intermediate_python.md


markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

plugins:
  - include-markdown
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ramonpzg/rpg_content
      name: Github
    - icon: material/email
      link: "mailto:ramonpzg01@gmail.com"